### ISSUE TITLE
Remove `px` from 0 values

### ISSUE THREAD

**Issue by jbsmith731** [melanieseifert/psd-to-css3#6]
Love this tool! Most linters prefer `px` to be omitted zero values.

Current: `box-shadow: 3px 4px 5px 0px rgba(0, 0, 0, 0.75); `

Proposed Change: `box-shadow: 3px 4px 5px 0 rgba(0, 0, 0, 0.75); `

**Comment by melanieseifert** [comment]
I agree that the px is preferred to be dropped when the value is zero, however, it is not invalid syntax for it to be there.  When I have time to make the necessary js updates to accommodate this, I will certainly do so.
